version: 0.2

phases:
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Executando migrations...
      - echo Create Database
      - npx sequelize db:create
      - echo Migrate Database
      - npx sequelize db:migrate
      - echo Build finalizado em `date`
